-- appearance
vim.cmd("colorscheme tokyonight")
vim.cmd("hi Normal guibg=none")
vim.cmd("hi NormalNC guibg=none")
--[[ vim.cmd("hi NormalFloat guibg=none") ]]
vim.cmd("hi FloatBorder guibg=None")
vim.cmd("hi clear SignColumn")
vim.cmd("hi clear SignColumn")
vim.cmd("hi clear TabLineFill")
vim.cmd("hi clear VertSplit")
vim.cmd("hi clear Tabline")
vim.cmd("hi Pmenu guibg=#161929")
vim.cmd("hi DiagnosticVirtualTextInfo guibg=None")
vim.cmd("hi DiagnosticVirtualTextError guibg=None")
vim.cmd("hi DiagnosticVirtualTextWarn guibg=None")
vim.cmd("hi DiagnosticVirtualTextHint guibg=None")
vim.cmd("hi DiagnosticVirtualTextHint guibg=None")
vim.cmd("hi @type.builtin guifg=#ad345c")
vim.cmd("hi @type guifg=#ad345c")
vim.cmd("hi @parameter guifg=#29a4bd")
vim.cmd("hi NvimTreeNormal guibg=None ctermbg=None")
vim.cmd("hi NvimTreeNormalNC guibg=None ctermbg=None")
vim.cmd("hi NvimTreeWinSeparator guibg=None ctermbg=None")
vim.cmd("hi TelescopeNormal guibg=None")
vim.cmd("hi TelescopeBorder guibg=None")
vim.cmd("hi TreesitterContext guibg=None")
vim.cmd("hi TreesitterContextBottom guibg=None")
vim.cmd("hi NormalFloat guibg=None")
vim.cmd("hi CopilotSuggestion guibg=None guifg=#565f89")
vim.cmd("hi Folded guibg=None")
vim.cmd("hi Pmenu guifg=#33328b guibg=None")
vim.cmd("hi PmenuSel guibg=#232748")
vim.cmd("hi TelescopeSelection guibg=#232748")
vim.cmd("hi Visual guibg=#232748")

require'colorizer'.setup()
